### ISSUE TITLE
Deduplicate methods that may apply to a checked out drive

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-sdk-rpc#2]
Clients will want to call some commands on the most recent version of a drive in some cases but an old checkout in other cases. As far as I can tell, these two cases require two different keys in `methods.json`. For example:

```json
"sdk.getDrive(url).get(path, options)"
"sdk.getDrive(url).checkout(version).get(path, options)"
```

To simplify the RPC API, what do you think about only using `"sdk.getDrive(url).checkout(version).get(path, options)"`, but when the `version` is falsy, treat the call like `"sdk.getDrive(url).get(path, options)"`?

**Comment by RangerMauve** [comment]
I'd prefer we have the two sets to reduce the difference between the js and rpc calls. We could do the non checkout version first then I can make a small script to generate the checkout versions and append them
