### ISSUE TITLE
How to handle streams?

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-sdk-rpc#3]
For example, `drive.diff` returns a stream which can be read with `for await ...`. One idea is to special case `drive.diff` in the RPC bridge by accepting two version numbers, getting the snapshot under the hood, and then sending back the big JSON diff.

**Comment by RangerMauve** [comment]
Could you elaborate on the version numbers thing? I think having a special case where we turn async iterators into arrays might be a good idea. 🤔

Are there other stream apis that are absolutely necessary right now?

**Comment by josephmturner** [comment]
> Could you elaborate on the version numbers thing? I think having a special case where we turn async iterators into arrays might be a good idea. 🤔

Something along the lines of [this hypercore-fetch PR](https://github.com/RangerMauve/hypercore-fetch/pull/90/files)?

> Are there other stream apis that are absolutely necessary right now?

Yes. `hypercore-fetch` also uses `drive.list` and `drive.readdir`, and I can imagine we'd want to use `drive.entries` at some point too.

**Comment by RangerMauve** [comment]
Insteadof streaming we'll read files into blobs with base64 encoding and use the filesystem for large files

**Comment by RangerMauve** [comment]
Instead I'll detect if the response is a stream, and turn it into a base64 blob for binary or an array for objects

**Comment by RangerMauve** [comment]
We turn streams into arrays.
