### ISSUE TITLE
Allow users to specify options for `sdk.getDrive()`

### ISSUE THREAD

**Issue by josephmturner** [RangerMauve/hyper-sdk-rpc#9]
In `methods.json`, should we specify the optional `autoJoin` and `sparse` flags in each method/property specification?

**Comment by RangerMauve** [comment]
Yes that would be useful. With the caveat that only the first invocation of `getDrive` for that url will take them into consideration

**Comment by josephmturner** [comment]
I will add a `driveOpts` argument to pass like `sdk.getDrive(url, driveOpts)` in each method that calls `sdk.getDrive(url)`.

**Comment by josephmturner** [comment]
Added in https://github.com/RangerMauve/hyper-sdk-rpc/pull/1/commits/6af6e577b4e1111100f46087b303315ccdf6c901.
